{
 "title": "Hello World",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Available Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"hello-world\"} / kube_deployment_status_replicas{deployment=\"hello-world\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"hello-world\"} / kube_deployment_status_replicas{deployment=\"hello-world\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"hello-world\"}) / sum(kube_deployment_status_replicas{deployment=\"hello-world\"}) * 100"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"hello-world\"})"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"hello-world\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"hello-world\"})"
    }
   ]
  },
  {
   "title": "Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(helloworld_request_count{}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests by route (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(helloworld_request_count{}[$__rate_interval])) by (route)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests by pod (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(helloworld_request_count{}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}