---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: hello-world
    prometheus: default
  name: hello-world
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      scrapeTimeout: 10s
      targetPort: 9762
  jobLabel: hello-world
  selector:
    matchLabels:
      app: hello-world
