---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-operator
  labels:
    app: hello-world-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-operator
  template:
    metadata:
      labels:
        app: hello-world-operator
    spec:
      serviceAccountName: hello-world-operator
      serviceAccount: hello-world-operator
      containers:
      - name: hello-world-operator
        image: registry.neon.local/library/hello-world-operator
        imagePullPolicy: Always
        ports:
          - name: http-web
            containerPort: 80
            protocol: TCP
          - name: http-metrics
            containerPort: 9762
            protocol: TCP
        env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-world-operator
rules:
- apiGroups:
  - demo.neonkube.io
  resources:
  - helloworlddemos
  verbs:
  - '*'
- apiGroups:
  - neonkube.io
  resources:
  - neonssoclients
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - integreatly.org
  resources:
  - grafanadashboards
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hello-world-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hello-world-operator
subjects:
- kind: ServiceAccount
  name: hello-world-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-world-operator
  namespace: default
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
  - ""
  resourceNames:
  - hello-world-operator-webhook-tls
  resources:
  - secrets
  verbs:
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-world-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hello-world-operator
subjects:
- kind: ServiceAccount
  name: hello-world-operator
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: hello-world-operator
    prometheus: default
  name: hello-world-operator
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      scrapeTimeout: 2s
      targetPort: 9762
  jobLabel: hello-world-operator
  selector:
    matchLabels:
      app: hello-world-operator
