---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      volumes:
        - name: config
          configMap:
            name: load-generator
      containers:
      - name: load-generator
        image: ghcr.io/neonkube-dev/load-generator:neonkube-0.3.0-alpha 
        env:
          - name: REQUESTS_PER_SECOND
            value: "10"
        ports:
          - name: http-web
            containerPort: 80
            protocol: TCP
          - name: http-metrics
            containerPort: 9762
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /etc/load-generator
        livenessProbe:
          exec:
            command:
              - /health-check
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /ready-check
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          exec:
            command:
              - /health-check
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 30
