---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  labels:
    app: weather-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: weather-api
        image: neon-registry.0c51e652ca1adbbc.neoncluster.io/library/weather-api:latest
        ports:
          - name: http-web
            containerPort: 80
            protocol: TCP
          - name: http-metrics
            containerPort: 9762
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - /health-check
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /ready-check
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          exec:
            command:
              - /health-check
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api
  labels:
    app: weather-api
spec:
  selector:
    app: weather-api
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-metrics
      protocol: TCP
      port: 9762
      targetPort: 9762
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: weather-api
    prometheus: default
  name: weather-api
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      scrapeTimeout: 10s
      targetPort: 9762
  jobLabel: weather-api
  selector:
    matchLabels:
      app: weather-api