{
 "title": "Hello, World!",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "Information, Error, Debug, Trace, Warning"
   }
  ]
 },
 "panels": [
  { "title": "Deployment Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"hello-world\"} / kube_deployment_status_replicas{deployment=\"hello-world\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"hello-world\"} / kube_deployment_status_replicas{deployment=\"hello-world\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"hello-world\"}) / sum(kube_deployment_status_replicas{deployment=\"hello-world\"}) * 100"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"hello-world\"})"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"hello-world\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"hello-world\"}) by (container) > 0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"hello-world\"})"
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{}[$__rate_interval])) by (exported_endpoint)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{code=~\"400|500\"}[$__rate_interval])) by (route, code)",
     "legendFormat": "{{code}} {{action}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (route, code, le))",
     "legendFormat": "P50 - {{route}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (route, code, le))",
     "legendFormat": "P90 - {{route}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (route, code, le))",
     "legendFormat": "P99 - {{route}}/{{code}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app=\"hello-world\"} |= `` | json | line_format `[{{.pod}}] [{{.severity}}] {{.body}}` | severity=~`$log_level`",
     "maxLines": 50
    }
   ]
  }
 ]
}